name: memology-server

services:
  redis:
    image: redis:7-alpine
    container_name: memology-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  memology-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memology-api
    ports:
      - "8001:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_HOST=http://192.168.0.123:11434
      - SD_BASE_URL=http://192.168.0.123:7860
      - WORKER_SECRET_TOKEN=IQ8P!pa%9jQW5FOMJMzV!A3HbTzJA5Hu
      - OUTPUT_DIR=/app/generated_images
    volumes:
      - ./src:/app/src
      - ./generated_images:/app/generated_images
      - ./logging.ini:/app/logging.ini
    depends_on:
      - redis

  memology-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memology-beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    command: celery -A src.worker.celery_app beat --loglevel=info

  memology-flower:
    image: mher/flower:2.0
    container_name: memology-flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    stop_grace_period: 1m

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3101:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://95.131.149.248:7080/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true  
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  redis_data:
  loki_data:
  grafana_data:
